[build]
target = "x86_64-blog_os.json"
#target = "x86_64-blog_os.toml"

[unstable]
json-target-spec = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.x86_64-blog_os]
rustflags = ['-Zlocation-detail=none', '-Zfmt-debug=none', '--cfg', 'getrandom_backend="rdrand"']
